### PR TITLE
Bump ruby -v to 3.1.0

### PR DESCRIPTION
**Pull request by emp823**
Have to discuss order of operations first, but necessary to bump the ruby version in main repo.

### CODE REVIEW

**Comment by emp823** [comment]
Simplest thing I can think of:
```
- name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/occupier/ruby-node:${{ github.sha }}

```

More advanced: https://github.com/docker/metadata-action

What do you think?

**Comment by krishantaylor** [comment]
I'm not sure about creating that many unique tags. The [package page](https://github.com/occupier/ruby-node-image/pkgs/container/ruby-node) could become unwieldy. I think another option that's more reusable is duplicating the workflow for a `next` branch that only runs on commits (and not a schedule) where the image is tagged with `next`. This branch can then be reused for other upgrades, and can always be merged in cleanly without disrupting the `latest` build.

**Comment by emp823** [comment]
I figured we would only create new builds when we need a new ruby version or otherwise change the dockerfile (on merge to main), is that not the case?

**Comment by krishantaylor** [comment]
The current setup runs on pushes and on a weekly schedule so that it gets regular updates from the base image and the other installed packages.

**Pull request closed without merging**
